name: Import Skills Badges

on:
  workflow_call:
    inputs:
      skills-boost-url:
        required: true
        type: string
      badge-count:
        required: true
        type: number
      repo-ref:
        required: true
        type: string

jobs:
  skills-boost-badges:
    name: Import Skills Boost badges at
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with: ${{ inputs.repo_ref }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax
          python-version: "3.x"
          architecture: "x64"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          ls
          python -m pip install --upgrade pip
          pip install -r ./gcp-skills-boost-badges/requirements.txt
      - name: Check for updated Skills Boost Badges
        run: python -u ./gcp-skills-boost-badges/import-skills-boost.py ${{ inputs.skills-boost-url }} ${{ inputs.badge-count }}
      - name: Commit and push
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "README-bot"
          git add -A
          git commit -m "Update badges" || git commit --allow-empty -m "Empty commit"
          git push
